/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as MeuAgendamentoRouteImport } from './routes/meu-agendamento'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as SuperAdminLoginRouteImport } from './routes/super-admin.login'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as BSlugIndexRouteImport } from './routes/b.$slug.index'
import { Route as BSlugServicosRouteImport } from './routes/b.$slug.servicos'
import { Route as BSlugPlanosRouteImport } from './routes/b.$slug.planos'
import { Route as BSlugMeuAgendamentoRouteImport } from './routes/b.$slug.meu-agendamento'
import { Route as BSlugEquipeRouteImport } from './routes/b.$slug.equipe'
import { Route as BSlugAgendarRouteImport } from './routes/b.$slug.agendar'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuAgendamentoRoute = MeuAgendamentoRouteImport.update({
  id: '/meu-agendamento',
  path: '/meu-agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/super-admin/',
  path: '/super-admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminLoginRoute = SuperAdminLoginRouteImport.update({
  id: '/super-admin/login',
  path: '/super-admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugIndexRoute = BSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BSlugRoute,
} as any)
const BSlugServicosRoute = BSlugServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => BSlugRoute,
} as any)
const BSlugPlanosRoute = BSlugPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => BSlugRoute,
} as any)
const BSlugMeuAgendamentoRoute = BSlugMeuAgendamentoRouteImport.update({
  id: '/meu-agendamento',
  path: '/meu-agendamento',
  getParentRoute: () => BSlugRoute,
} as any)
const BSlugEquipeRoute = BSlugEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => BSlugRoute,
} as any)
const BSlugAgendarRoute = BSlugAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => BSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/equipe': typeof EquipeRoute
  '/login': typeof LoginRoute
  '/meu-agendamento': typeof MeuAgendamentoRoute
  '/painel': typeof PainelRoute
  '/planos': typeof PlanosRoute
  '/servicos': typeof ServicosRoute
  '/b/$slug': typeof BSlugRouteWithChildren
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/b/$slug/agendar': typeof BSlugAgendarRoute
  '/b/$slug/equipe': typeof BSlugEquipeRoute
  '/b/$slug/meu-agendamento': typeof BSlugMeuAgendamentoRoute
  '/b/$slug/planos': typeof BSlugPlanosRoute
  '/b/$slug/servicos': typeof BSlugServicosRoute
  '/b/$slug/': typeof BSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/equipe': typeof EquipeRoute
  '/login': typeof LoginRoute
  '/meu-agendamento': typeof MeuAgendamentoRoute
  '/painel': typeof PainelRoute
  '/planos': typeof PlanosRoute
  '/servicos': typeof ServicosRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/b/$slug/agendar': typeof BSlugAgendarRoute
  '/b/$slug/equipe': typeof BSlugEquipeRoute
  '/b/$slug/meu-agendamento': typeof BSlugMeuAgendamentoRoute
  '/b/$slug/planos': typeof BSlugPlanosRoute
  '/b/$slug/servicos': typeof BSlugServicosRoute
  '/b/$slug': typeof BSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/equipe': typeof EquipeRoute
  '/login': typeof LoginRoute
  '/meu-agendamento': typeof MeuAgendamentoRoute
  '/painel': typeof PainelRoute
  '/planos': typeof PlanosRoute
  '/servicos': typeof ServicosRoute
  '/b/$slug': typeof BSlugRouteWithChildren
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/b/$slug/agendar': typeof BSlugAgendarRoute
  '/b/$slug/equipe': typeof BSlugEquipeRoute
  '/b/$slug/meu-agendamento': typeof BSlugMeuAgendamentoRoute
  '/b/$slug/planos': typeof BSlugPlanosRoute
  '/b/$slug/servicos': typeof BSlugServicosRoute
  '/b/$slug/': typeof BSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/equipe'
    | '/login'
    | '/meu-agendamento'
    | '/painel'
    | '/planos'
    | '/servicos'
    | '/b/$slug'
    | '/super-admin/login'
    | '/super-admin/'
    | '/b/$slug/agendar'
    | '/b/$slug/equipe'
    | '/b/$slug/meu-agendamento'
    | '/b/$slug/planos'
    | '/b/$slug/servicos'
    | '/b/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/equipe'
    | '/login'
    | '/meu-agendamento'
    | '/painel'
    | '/planos'
    | '/servicos'
    | '/super-admin/login'
    | '/super-admin'
    | '/b/$slug/agendar'
    | '/b/$slug/equipe'
    | '/b/$slug/meu-agendamento'
    | '/b/$slug/planos'
    | '/b/$slug/servicos'
    | '/b/$slug'
  id:
    | '__root__'
    | '/'
    | '/agendar'
    | '/equipe'
    | '/login'
    | '/meu-agendamento'
    | '/painel'
    | '/planos'
    | '/servicos'
    | '/b/$slug'
    | '/super-admin/login'
    | '/super-admin/'
    | '/b/$slug/agendar'
    | '/b/$slug/equipe'
    | '/b/$slug/meu-agendamento'
    | '/b/$slug/planos'
    | '/b/$slug/servicos'
    | '/b/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendarRoute: typeof AgendarRoute
  EquipeRoute: typeof EquipeRoute
  LoginRoute: typeof LoginRoute
  MeuAgendamentoRoute: typeof MeuAgendamentoRoute
  PainelRoute: typeof PainelRoute
  PlanosRoute: typeof PlanosRoute
  ServicosRoute: typeof ServicosRoute
  BSlugRoute: typeof BSlugRouteWithChildren
  SuperAdminLoginRoute: typeof SuperAdminLoginRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-agendamento': {
      id: '/meu-agendamento'
      path: '/meu-agendamento'
      fullPath: '/meu-agendamento'
      preLoaderRoute: typeof MeuAgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/super-admin'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/login': {
      id: '/super-admin/login'
      path: '/super-admin/login'
      fullPath: '/super-admin/login'
      preLoaderRoute: typeof SuperAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug/': {
      id: '/b/$slug/'
      path: '/'
      fullPath: '/b/$slug/'
      preLoaderRoute: typeof BSlugIndexRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/b/$slug/servicos': {
      id: '/b/$slug/servicos'
      path: '/servicos'
      fullPath: '/b/$slug/servicos'
      preLoaderRoute: typeof BSlugServicosRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/b/$slug/planos': {
      id: '/b/$slug/planos'
      path: '/planos'
      fullPath: '/b/$slug/planos'
      preLoaderRoute: typeof BSlugPlanosRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/b/$slug/meu-agendamento': {
      id: '/b/$slug/meu-agendamento'
      path: '/meu-agendamento'
      fullPath: '/b/$slug/meu-agendamento'
      preLoaderRoute: typeof BSlugMeuAgendamentoRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/b/$slug/equipe': {
      id: '/b/$slug/equipe'
      path: '/equipe'
      fullPath: '/b/$slug/equipe'
      preLoaderRoute: typeof BSlugEquipeRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/b/$slug/agendar': {
      id: '/b/$slug/agendar'
      path: '/agendar'
      fullPath: '/b/$slug/agendar'
      preLoaderRoute: typeof BSlugAgendarRouteImport
      parentRoute: typeof BSlugRoute
    }
  }
}

interface BSlugRouteChildren {
  BSlugAgendarRoute: typeof BSlugAgendarRoute
  BSlugEquipeRoute: typeof BSlugEquipeRoute
  BSlugMeuAgendamentoRoute: typeof BSlugMeuAgendamentoRoute
  BSlugPlanosRoute: typeof BSlugPlanosRoute
  BSlugServicosRoute: typeof BSlugServicosRoute
  BSlugIndexRoute: typeof BSlugIndexRoute
}

const BSlugRouteChildren: BSlugRouteChildren = {
  BSlugAgendarRoute: BSlugAgendarRoute,
  BSlugEquipeRoute: BSlugEquipeRoute,
  BSlugMeuAgendamentoRoute: BSlugMeuAgendamentoRoute,
  BSlugPlanosRoute: BSlugPlanosRoute,
  BSlugServicosRoute: BSlugServicosRoute,
  BSlugIndexRoute: BSlugIndexRoute,
}

const BSlugRouteWithChildren = BSlugRoute._addFileChildren(BSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendarRoute: AgendarRoute,
  EquipeRoute: EquipeRoute,
  LoginRoute: LoginRoute,
  MeuAgendamentoRoute: MeuAgendamentoRoute,
  PainelRoute: PainelRoute,
  PlanosRoute: PlanosRoute,
  ServicosRoute: ServicosRoute,
  BSlugRoute: BSlugRouteWithChildren,
  SuperAdminLoginRoute: SuperAdminLoginRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
