/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as MeuAgendamentoRouteImport } from './routes/meu-agendamento'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as IndexRouteImport } from './routes/index'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuAgendamentoRoute = MeuAgendamentoRouteImport.update({
  id: '/meu-agendamento',
  path: '/meu-agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/equipe': typeof EquipeRoute
  '/login': typeof LoginRoute
  '/meu-agendamento': typeof MeuAgendamentoRoute
  '/painel': typeof PainelRoute
  '/planos': typeof PlanosRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/equipe': typeof EquipeRoute
  '/login': typeof LoginRoute
  '/meu-agendamento': typeof MeuAgendamentoRoute
  '/painel': typeof PainelRoute
  '/planos': typeof PlanosRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/equipe': typeof EquipeRoute
  '/login': typeof LoginRoute
  '/meu-agendamento': typeof MeuAgendamentoRoute
  '/painel': typeof PainelRoute
  '/planos': typeof PlanosRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/equipe'
    | '/login'
    | '/meu-agendamento'
    | '/painel'
    | '/planos'
    | '/servicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/equipe'
    | '/login'
    | '/meu-agendamento'
    | '/painel'
    | '/planos'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/agendar'
    | '/equipe'
    | '/login'
    | '/meu-agendamento'
    | '/painel'
    | '/planos'
    | '/servicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendarRoute: typeof AgendarRoute
  EquipeRoute: typeof EquipeRoute
  LoginRoute: typeof LoginRoute
  MeuAgendamentoRoute: typeof MeuAgendamentoRoute
  PainelRoute: typeof PainelRoute
  PlanosRoute: typeof PlanosRoute
  ServicosRoute: typeof ServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-agendamento': {
      id: '/meu-agendamento'
      path: '/meu-agendamento'
      fullPath: '/meu-agendamento'
      preLoaderRoute: typeof MeuAgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendarRoute: AgendarRoute,
  EquipeRoute: EquipeRoute,
  LoginRoute: LoginRoute,
  MeuAgendamentoRoute: MeuAgendamentoRoute,
  PainelRoute: PainelRoute,
  PlanosRoute: PlanosRoute,
  ServicosRoute: ServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
